### ISSUE TITLE
Extension breaks hyperlinks to files

### ISSUE THREAD

**Issue by gabeklavans** [sgbush/buildoutputcolorizer#2]
Enabling the extension disables the ability to click on paths to files in the output to have vscode take you to that file/line in the file quickly.

**Comment by sgbush** [comment]
The fix for this is in progress.  Unfortunately it is slow going since the TextMate grammar for hyperlinks is not the easiest to understand nor that well documented.

**Comment by deanqx** [comment]
Extensions like "Output Colorizer" have done this before, maybe take a look in that source code

**Comment by sgbush** [comment]
Still looking at this issue.  It does not appear that it can be fixed with pattern matching, i.e. TextMate rules.  Will be looking into Output window rendering code to see how hyperlinks are implemented.  Thanks for the suggestion @deanqx

**Comment by sgbush** [comment]
Thank you for your patience.  I have pushed a new version that should fix this issue.

**Comment by deanqx** [comment]
Will try it some day

**Comment by DanielNovelda** [comment]
Works now, thanks 👍
