### ISSUE TITLE
MSVC Link errors

### ISSUE THREAD

**Issue by Zitrax** [sgbush/buildoutputcolorizer#3]
Would be nice if they were also colorized, for example lines like:

```
[build] MyFile.cpp.obj : error LNK2005: "class std::shared_ptr<class Foo> __cdecl Bar(void)" (?Baz@XX@YY@@YA?AV?$shared_ptr@VBar@XX@YY@@@std@@XZ) already defined in MyOtherFile.cpp.obj
```

**Comment by sgbush** [comment]
Thanks for the example.  I will try to get it added in the next few days

**Comment by sgbush** [comment]
Thank you for your suggestion.  I have pushed a new version that includes this syntax.
