### ISSUE TITLE
Support for ANSI Colors

### ISSUE THREAD

**Issue by deanqx** [sgbush/buildoutputcolorizer#4]
### When using these CMake commands you should get colored outputs:

````
if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    add_compile_options(-fdiagnostics-color=always)
elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    add_compile_options(-fcolor-diagnostics)
endif()
````

### Until now there is no fix from Microsoft's side.

![image](https://user-images.githubusercontent.com/110404616/231605240-48f70898-e512-44f0-9d2e-f659eea60474.png)

**Comment by sgbush** [comment]
Thank you for your submission.  This is a know issue in the VSCode output window.  Please disable compiler-generated terminal color codes and use only a colorizer extension such as this one.
